import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "runyankole" | "rukiga" | "runyoro" | "rutooro";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.findVets": "Find Vets",
    "nav.login": "Login",
    "nav.getStarted": "Get Started",
    "nav.dashboard": "Dashboard",
    "nav.messages": "Messages",
    "nav.profile": "Profile",
    "nav.signOut": "Sign Out",
    "nav.myAccount": "My Account",
    
    // Find Vets Page
    "findVets.title": "Find Veterinarians",
    "findVets.subtitle": "Discover qualified veterinarians in your area",
    "findVets.searchPlaceholder": "Search by name, location, or specialization...",
    "findVets.vetLocations": "Vet Locations",
    "findVets.found": "Found",
    "findVets.veterinarian": "Veterinarian",
    "findVets.veterinarians": "Veterinarians",
    "findVets.noVets": "No veterinarians found",
    "findVets.noLocationData": "No veterinarians with location data available",
    "findVets.viewProfile": "View Profile",
    "findVets.verified": "Verified",
    "findVets.available": "Available",
    "findVets.online": "Online Now",
    "findVets.offline": "Offline",
    "findVets.failedToLoad": "Failed to load veterinarians",
    
    // Farmer Dashboard
    "farmerDashboard.title": "Farmer Dashboard",
    "farmerDashboard.subtitle": "Manage your animals and consultations",
    "farmerDashboard.requestConsultation": "Request Consultation",
    "farmerDashboard.requestConsultationDesc": "Get expert veterinary advice for your animals",
    "farmerDashboard.manageAnimals": "Manage Animals",
    "farmerDashboard.manageAnimalsDesc": "Add or update your animal records",
    "farmerDashboard.totalAnimals": "Total Animals",
    "farmerDashboard.pendingConsultations": "Pending Consultations",
    "farmerDashboard.completedConsultations": "Completed Consultations",
    "farmerDashboard.recentConsultations": "Recent Consultations",
    "farmerDashboard.recentConsultationsDesc": "Your latest consultation requests",
    "farmerDashboard.noConsultations": "No consultations yet",
    "farmerDashboard.firstConsultation": "Request Your First Consultation",
    "farmerDashboard.viewDetails": "View Details",
    "farmerDashboard.created": "Created",
    
    // Vet Dashboard
    "vetDashboard.title": "Veterinarian Dashboard",
    "vetDashboard.subtitle": "Manage consultations and help farmers",
    "vetDashboard.pendingConsultations": "Pending Consultations",
    "vetDashboard.inProgress": "In Progress",
    "vetDashboard.completed": "Completed",
    "vetDashboard.pending": "Pending",
    "vetDashboard.myCases": "My Cases",
    "vetDashboard.availableConsultations": "Available Consultations",
    "vetDashboard.availableConsultationsDesc": "Accept consultations to start helping farmers",
    "vetDashboard.noPending": "No pending consultations at the moment",
    "vetDashboard.myConsultations": "My Consultations",
    "vetDashboard.myConsultationsDesc": "Consultations you're currently managing",
    "vetDashboard.noAccepted": "You haven't accepted any consultations yet",
    "vetDashboard.acceptCase": "Accept Case to View Details",
    "vetDashboard.manageCase": "Manage Case",
    "vetDashboard.requested": "Requested",
    "vetDashboard.started": "Started",
    
    // New Consultation
    "consultation.title": "Request Veterinary Consultation",
    "consultation.subtitle": "Fill out the form below to request professional veterinary advice",
    "consultation.selectAnimal": "Select Animal",
    "consultation.chooseAnimal": "Choose an animal",
    "consultation.noAnimals": "No animals registered.",
    "consultation.addAnimalFirst": "Add an animal first",
    "consultation.subject": "Subject",
    "consultation.subjectPlaceholder": "Brief description of the issue",
    "consultation.urgencyLevel": "Urgency Level",
    "consultation.selectUrgency": "Select urgency",
    "consultation.urgencyLow": "Low - Routine checkup",
    "consultation.urgencyMedium": "Medium - Needs attention soon",
    "consultation.urgencyHigh": "High - Urgent care needed",
    "consultation.urgencyEmergency": "Emergency - Critical condition",
    "consultation.symptoms": "Symptoms",
    "consultation.symptomsPlaceholder": "Describe any symptoms you've observed",
    "consultation.description": "Detailed Description",
    "consultation.descriptionPlaceholder": "Provide detailed information about the animal's condition, behavior, and any other relevant details",
    "consultation.uploadImages": "Upload Images (Optional)",
    "consultation.clickToUpload": "Click to upload images (max 5)",
    "consultation.imagesSelected": "image(s) selected",
    "consultation.cancel": "Cancel",
    "consultation.submitRequest": "Submit Request",
    "consultation.uploading": "Uploading...",
    "consultation.submitting": "Submitting...",
    "consultation.success": "Consultation request submitted successfully",
    
    // Profile Page
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your account information and preferences",
    "profile.email": "Email",
    "profile.emailCannotChange": "Email cannot be changed",
    "profile.fullName": "Full Name",
    "profile.fullNamePlaceholder": "Enter your full name",
    "profile.phoneNumber": "Phone Number",
    "profile.phonePlaceholder": "Enter your phone number",
    "profile.updateProfile": "Update Profile",
    "profile.updating": "Updating...",
    "profile.updated": "Profile updated",
    "profile.updatedSuccess": "Your profile has been updated successfully.",
    "profile.photoUpdated": "Profile photo updated",
    "profile.photoUpdatedSuccess": "Your profile photo has been updated successfully.",
    "profile.security": "Security Settings",
    "profile.securityDesc": "Manage two-factor authentication for your account",
    "profile.googleAuth": "Google Authenticator",
    "profile.mfaEnabled": "Two-factor authentication is enabled",
    "profile.mfaDisabled": "Add extra security by requiring a code from your phone",
    "profile.enable": "Enable",
    
    // Authentication - Login
    "auth.welcomeBack": "Welcome Back",
    "auth.loginSubtitle": "Login to access your VetConnect account",
    "auth.email": "Email",
    "auth.emailPlaceholder": "your@email.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "••••••••",
    "auth.continueWithAuth": "Continue with Authenticator",
    "auth.temporarilyLocked": "Temporarily Locked",
    "auth.verifying": "Verifying...",
    "auth.noAccount": "Don't have an account?",
    "auth.registerHere": "Register here",
    "auth.authenticatorCode": "Authenticator Code",
    "auth.enterCode": "Enter the 6-digit code from Google Authenticator",
    "auth.verificationCode": "Verification Code",
    "auth.enterCodeFromApp": "Enter code from Google Authenticator",
    "auth.verifyAndLogin": "Verify & Login",
    "auth.back": "Back",
    "auth.invalidCode": "Invalid Code",
    "auth.enterSixDigits": "Please enter a 6-digit code",
    "auth.validationError": "Validation Error",
    "auth.loginSuccess": "Login Successful",
    "auth.mfaReminder": "Consider enabling Google Authenticator for extra security",
    "auth.enterAuthCode": "Enter Authenticator Code",
    "auth.openAuthApp": "Open Google Authenticator and enter the 6-digit code",
    "auth.mfaSuccess": "Logged in successfully with Google Authenticator",
    "auth.timeRemaining": "Time remaining",
    
    // Authentication - Register
    "auth.createAccount": "Create Account",
    "auth.registerSubtitle": "Join VetConnect to access veterinary care",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Aaron Kwesiga",
    "auth.confirmPassword": "Confirm Password",
    "auth.iAmA": "I am a:",
    "auth.farmerPetOwner": "Farmer / Pet Owner",
    "auth.farmerDesc": "I need veterinary consultations for my animals",
    "auth.veterinarian": "Veterinarian",
    "auth.vetDesc": "I want to provide veterinary consultations",
    "auth.creatingAccount": "Creating account...",
    "auth.accountCreated": "Account created successfully!",
    "auth.hasAccount": "Already have an account?",
    "auth.loginHere": "Login here",
    
    // Validation messages
    "auth.invalidEmail": "Invalid email address",
    "auth.passwordMinLength": "Password must be at least 6 characters",
    "auth.nameMinLength": "Name must be at least 2 characters",
    "auth.passwordsNoMatch": "Passwords don't match",
    
    // Animals Management
    "animals.title": "My Animals",
    "animals.subtitle": "Manage your animal records",
    "animals.addAnimal": "Add Animal",
    "animals.editAnimal": "Edit Animal",
    "animals.deleteAnimal": "Delete Animal",
    "animals.name": "Name",
    "animals.type": "Type",
    "animals.breed": "Breed",
    "animals.age": "Age",
    "animals.weight": "Weight (kg)",
    "animals.medicalHistory": "Medical History",
    "animals.noAnimals": "No animals registered yet",
    "animals.addFirst": "Add your first animal",
    
    // Status labels
    "status.pending": "Pending",
    "status.inProgress": "In Progress",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    
    // Urgency labels
    "urgency.low": "Low",
    "urgency.medium": "Medium",
    "urgency.high": "High",
    "urgency.emergency": "Emergency",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.submit": "Submit",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.unnamed": "Unnamed",
    "common.years": "years",
    "common.months": "months",
    "common.you": "You",
    
    // Messaging
    "messaging.title": "Messages",
    "messaging.subtitle": "Your consultation conversations",
    "messaging.noMessages": "No Messages Yet",
    "messaging.noMessagesDesc": "Start a consultation to begin messaging with a veterinarian.",
    "messaging.pendingAssignment": "Pending Assignment",
    "messaging.consultationMessages": "Consultation Messages",
    "messaging.typeMessage": "Type your message...",
    "messaging.sendMessage": "Send message",
    
    // Consultation Detail
    "consultationDetail.requestedOn": "Requested on",
    "consultationDetail.assignedVet": "Assigned Veterinarian",
    "consultationDetail.description": "Description",
    "consultationDetail.symptoms": "Symptoms",
    "consultationDetail.images": "Images",
    "consultationDetail.back": "Back",
    "consultationDetail.failedToLoad": "Failed to load consultation",
    "consultationDetail.diagnosis": "Diagnosis",
    "consultationDetail.treatmentPlan": "Treatment Plan",
    "consultationDetail.followUpNotes": "Follow-up Notes",
    
    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    
    // Language names
    "lang.en": "English",
    "lang.runyankole": "Runyankole",
    "lang.rukiga": "Rukiga",
    "lang.runyoro": "Runyoro",
    "lang.rutooro": "Rutooro",
  },
  runyankole: {
    // Navigation
    "nav.findVets": "Shanga Abashaaho",
    "nav.login": "Yingira",
    "nav.getStarted": "Tandika",
    "nav.dashboard": "Ekibaho",
    "nav.messages": "Obubaka",
    "nav.profile": "Ebikukwataho",
    "nav.signOut": "Fuluma",
    "nav.myAccount": "Akauntu Yange",
    
    // Find Vets Page
    "findVets.title": "Shanga Abashaaho",
    "findVets.subtitle": "Kushanga abashaaho abakugu omu kitundu kyawe",
    "findVets.searchPlaceholder": "Shanga na izina, ehantu nari obumanyi...",
    "findVets.vetLocations": "Ahantu h'Abashaaho",
    "findVets.found": "Bashangiwe",
    "findVets.veterinarian": "Omushaaho",
    "findVets.veterinarians": "Abashaaho",
    "findVets.noVets": "Tihariho abashaaho bashangiwe",
    "findVets.noLocationData": "Tihariho abashaaho abaine ehantu haabo",
    "findVets.viewProfile": "Laba Ebikumukwataho",
    "findVets.verified": "Akakasizibwe",
    "findVets.available": "Aliho",
    "findVets.online": "Ariho Hati",
    "findVets.offline": "Tarikuriho",
    "findVets.failedToLoad": "Okureeba abashaaho kuremereire",
    
    // Farmer Dashboard
    "farmerDashboard.title": "Ekibaho ky'Omuhingi",
    "farmerDashboard.subtitle": "Kurondoora ebyonyi byawe n'okubuuza",
    "farmerDashboard.requestConsultation": "Saba Okubuuza",
    "farmerDashboard.requestConsultationDesc": "Fumura obujanjabi bw'abashaaho obu ebyonyi byawe",
    "farmerDashboard.manageAnimals": "Rondoora Ebyonyi",
    "farmerDashboard.manageAnimalsDesc": "Yongyera nari hindura amakuru g'ebyonyi byawe",
    "farmerDashboard.totalAnimals": "Ebyonyi Byona",
    "farmerDashboard.pendingConsultations": "Okubuuza Okutari Kuhindurwa",
    "farmerDashboard.completedConsultations": "Okubuuza Okurangire",
    "farmerDashboard.recentConsultations": "Okubuuza Okushya",
    "farmerDashboard.recentConsultationsDesc": "Okubuuza kwawe okw'ekiseera kino",
    "farmerDashboard.noConsultations": "Tihariho okubuuza",
    "farmerDashboard.firstConsultation": "Saba Okubuuza Kwonka Okwa Mbere",
    "farmerDashboard.viewDetails": "Laba Ebirikukwataho",
    "farmerDashboard.created": "Yatondekwa",
    
    // Vet Dashboard
    "vetDashboard.title": "Ekibaho ky'Omushaaho",
    "vetDashboard.subtitle": "Kurondoora okubuuza n'okuyambira abahingi",
    "vetDashboard.pendingConsultations": "Okubuuza Okutari Kuhindurwa",
    "vetDashboard.inProgress": "Nikukorerwa",
    "vetDashboard.completed": "Kurangire",
    "vetDashboard.pending": "Okutari Kuhindurwa",
    "vetDashboard.myCases": "Ebintu Byange",
    "vetDashboard.availableConsultations": "Okubuuza Okuri",
    "vetDashboard.availableConsultationsDesc": "Kwikira okubuuza kutandike okuyambira abahingi",
    "vetDashboard.noPending": "Tihariho okubuuza okutari kuhindurwa ekiseera kino",
    "vetDashboard.myConsultations": "Okubuuza Kwange",
    "vetDashboard.myConsultationsDesc": "Okubuuza okuri kukurondoora",
    "vetDashboard.noAccepted": "Tikwetirizire okubuuza kwona",
    "vetDashboard.acceptCase": "Kwikira Kulabe Ebirikukwataho",
    "vetDashboard.manageCase": "Rondoora Ekintu",
    "vetDashboard.requested": "Kyasabwa",
    "vetDashboard.started": "Kyatandikire",
    
    // New Consultation
    "consultation.title": "Saba Okubuuza Omushaaho",
    "consultation.subtitle": "Ijuza fomu eno osabe obujanjabi bw'abashaaho",
    "consultation.selectAnimal": "Salira Ekyonyi",
    "consultation.chooseAnimal": "Salira ekyonyi",
    "consultation.noAnimals": "Tihariho ebyonyi byandikishirizibwe.",
    "consultation.addAnimalFirst": "Yongyera ekyonyi ky'okubanza",
    "consultation.subject": "Omutwe",
    "consultation.subjectPlaceholder": "Ekimanyiso ekiguhi ky'ekizibu",
    "consultation.urgencyLevel": "Omutindo gw'Obuhiise",
    "consultation.selectUrgency": "Salira obuhiise",
    "consultation.urgencyLow": "Omutindo gw'ansi - Okulaba okw'obwire",
    "consultation.urgencyMedium": "Omutindo gw'akati - Kikwetaagisa hati hati",
    "consultation.urgencyHigh": "Omutindo gw'waiguru - Obujanjabi obuhiise",
    "consultation.urgencyEmergency": "Emergenci - Embeera y'akabi",
    "consultation.symptoms": "Obumanyiso",
    "consultation.symptomsPlaceholder": "Nyomora obumanyiso obwarabire",
    "consultation.description": "Amakuru Agamaizi",
    "consultation.descriptionPlaceholder": "Hereza amakuru agamaizi agakwata ku mbeera y'ekyonyi, enzobaano yako, n'ebindi",
    "consultation.uploadImages": "Teeka Ebifaananyi (Kwonka)",
    "consultation.clickToUpload": "Nyiga oteeke ebifaananyi (5 bya waiguru)",
    "consultation.imagesSelected": "ebifaananyi bisaliirwe",
    "consultation.cancel": "Rekaho",
    "consultation.submitRequest": "Werekeze Okusaba",
    "consultation.uploading": "Nikuteeka...",
    "consultation.submitting": "Nikuwerekeza...",
    "consultation.success": "Okusaba kwawe kwashemereziibwe bulungi",
    
    // Profile Page
    "profile.title": "Ebyensimbisa by'Ebikukwataho",
    "profile.subtitle": "Rondoora amakuru g'akauntu yawe n'ebyokwenda",
    "profile.email": "Email",
    "profile.emailCannotChange": "Email teyenda kuhindurwa",
    "profile.fullName": "Eizina Ryona",
    "profile.fullNamePlaceholder": "Andika eizina ryawe ryona",
    "profile.phoneNumber": "Esimu Namba",
    "profile.phonePlaceholder": "Andika esimu namba yawe",
    "profile.updateProfile": "Hindura Ebikukwataho",
    "profile.updating": "Nikuhindura...",
    "profile.updated": "Ebikukwataho bihindurirwe",
    "profile.updatedSuccess": "Ebikukwataho byawe bihindurirwe bulungi.",
    "profile.photoUpdated": "Ekifaananyi kihindurirwe",
    "profile.photoUpdatedSuccess": "Ekifaananyi kyawe kihindurirwe bulungi.",
    "profile.security": "Ebyensimbisa by'Obukumi",
    "profile.securityDesc": "Rondoora obukumi obu enzira ebbiri",
    "profile.googleAuth": "Google Authenticator",
    "profile.mfaEnabled": "Obukumi obu enzira ebbiri bushemererizibwe",
    "profile.mfaDisabled": "Yongyera obukumi obungi n'okwetaaga kodi okuva ku simu yawe",
    "profile.enable": "Shemerereza",
    
    // Authentication - Login
    "auth.welcomeBack": "Ogarukire",
    "auth.loginSubtitle": "Yingira okwetooke akauntu yawe eya VetConnect",
    "auth.email": "Email",
    "auth.emailPlaceholder": "email@yawe.com",
    "auth.password": "Ekigambo ky'Obukuumi",
    "auth.passwordPlaceholder": "••••••••",
    "auth.continueWithAuth": "Twesegye n'Authenticator",
    "auth.temporarilyLocked": "Kizibizibwe Okw'Ekiseera",
    "auth.verifying": "Nikukakasa...",
    "auth.noAccount": "Otaine akauntu?",
    "auth.registerHere": "Wandiishe hanu",
    "auth.authenticatorCode": "Kodi y'Authenticator",
    "auth.enterCode": "Andika kodi y'ennamba 6 okuva mu Google Authenticator",
    "auth.verificationCode": "Kodi y'Okukakasa",
    "auth.enterCodeFromApp": "Andika kodi okuva mu Google Authenticator",
    "auth.verifyAndLogin": "Kakasa Oyingire",
    "auth.back": "Garuka",
    "auth.invalidCode": "Kodi Etari Kuhurikira",
    "auth.enterSixDigits": "Andika kodi y'ennamba 6",
    "auth.validationError": "Ensobi y'Okukakasa",
    "auth.loginSuccess": "Okuyingira Kubuzire",
    "auth.mfaReminder": "Fukirira okushemerereza Google Authenticator obu obukuumi obweyongerye",
    "auth.enterAuthCode": "Andika Kodi y'Authenticator",
    "auth.openAuthApp": "Huura Google Authenticator wandike kodi y'ennamba 6",
    "auth.mfaSuccess": "Waayingire bulungi na Google Authenticator",
    "auth.timeRemaining": "Ekiseera ekisigire",
    
    // Authentication - Register
    "auth.createAccount": "Tonda Akauntu",
    "auth.registerSubtitle": "Yegatte VetConnect obone obujanjabi bw'ebyonyi",
    "auth.fullName": "Eizina Ryona",
    "auth.fullNamePlaceholder": "Abiira Kwesiga",
    "auth.confirmPassword": "Kakasa Ekigambo ky'Obukuumi",
    "auth.iAmA": "Ndi:",
    "auth.farmerPetOwner": "Omuhingi / Nyine Ebyonyi",
    "auth.farmerDesc": "Neetaaga okubuuza obu ebyonyi byange",
    "auth.veterinarian": "Omushaaho",
    "auth.vetDesc": "Neenda okuha obujanjabi obu ebyonyi",
    "auth.creatingAccount": "Nikutonda akauntu...",
    "auth.accountCreated": "Akauntu yatondekwa bulungi!",
    "auth.hasAccount": "Oine akauntu?",
    "auth.loginHere": "Yingira hanu",
    
    // Validation messages
    "auth.invalidEmail": "Email etari kuhikira",
    "auth.passwordMinLength": "Ekigambo ky'obukuumi kikwetaagisa ennukuta 6",
    "auth.nameMinLength": "Eizina rikwetaagisa ennukuta 2",
    "auth.passwordsNoMatch": "Ebigambo by'obukuumi tibiri kukwatagana",
    
    // Animals Management
    "animals.title": "Ebyonyi Byange",
    "animals.subtitle": "Rondoora amakuru g'ebyonyi byawe",
    "animals.addAnimal": "Yongyera Ekyonyi",
    "animals.editAnimal": "Hindura Ekyonyi",
    "animals.deleteAnimal": "Siba Ekyonyi",
    "animals.name": "Eizina",
    "animals.type": "Ekika",
    "animals.breed": "Omuzaro",
    "animals.age": "Emyaka",
    "animals.weight": "Obuzito (kg)",
    "animals.medicalHistory": "Ebyafayo by'Obujanjabi",
    "animals.noAnimals": "Tihariho ebyonyi byandikishirizibwe",
    "animals.addFirst": "Yongyera ekyonyi kyawe eky'okubanza",
    
    // Status labels
    "status.pending": "Nikwekunda",
    "status.inProgress": "Nikukorerwa",
    "status.completed": "Kurangire",
    "status.cancelled": "Kwekizibwe",
    
    // Urgency labels
    "urgency.low": "Omutindo gw'ansi",
    "urgency.medium": "Omutindo gw'akati",
    "urgency.high": "Omutindo gw'waiguru",
    "urgency.emergency": "Emergenci",
    
    // Common
    "common.loading": "Nikureeba...",
    "common.error": "Ensobi",
    "common.success": "Kibuzire",
    "common.save": "Bika",
    "common.cancel": "Rekaho",
    "common.delete": "Siba",
    "common.edit": "Hindura",
    "common.submit": "Sindika",
    "common.required": "Kikwetaagisa",
    "common.optional": "Kwonka",
    "common.unnamed": "Etaine izina",
    "common.years": "emyaka",
    "common.months": "emyezi",
    "common.you": "Iwe",
    
    // Messaging
    "messaging.title": "Obubaka",
    "messaging.subtitle": "Ebiteekateko by'okubuuza kwawe",
    "messaging.noMessages": "Tihariho Bubaka",
    "messaging.noMessagesDesc": "Tandika okubuuza otandike okutumirana n'omushaaho.",
    "messaging.pendingAssignment": "Nikwetekyerezebwa",
    "messaging.consultationMessages": "Obubaka bw'Okubuuza",
    "messaging.typeMessage": "Andika obubaka bwawe...",
    "messaging.sendMessage": "Sindika obubaka",
    
    // Consultation Detail
    "consultationDetail.requestedOn": "Kwasabwa",
    "consultationDetail.assignedVet": "Omushaaho Owakwatirizibwa",
    "consultationDetail.description": "Ebirikukwataho",
    "consultationDetail.symptoms": "Obumanyiso",
    "consultationDetail.images": "Ebifaananyi",
    "consultationDetail.back": "Garuka",
    "consultationDetail.failedToLoad": "Kureeba okubuuza kuremere",
    "consultationDetail.diagnosis": "Okusanga Obulwaire",
    "consultationDetail.treatmentPlan": "Entekateeka y'Obujanjabi",
    "consultationDetail.followUpNotes": "Amakuru g'Okulondoora",
    
    // Theme
    "theme.light": "Ekitangaaza",
    "theme.dark": "Ekiziruguru",
    "theme.system": "System",
    
    // Language names
    "lang.en": "Engereza",
    "lang.runyankole": "Runyankole",
    "lang.rukiga": "Rukiga",
    "lang.runyoro": "Runyoro",
    "lang.rutooro": "Rutooro",
  },
  rukiga: {
    // Navigation
    "nav.findVets": "Shanga Abashaaho",
    "nav.login": "Yingira",
    "nav.getStarted": "Tandika",
    "nav.dashboard": "Ekibaho",
    "nav.messages": "Amabara",
    "nav.profile": "Ebikukwataho",
    "nav.signOut": "Vaaho",
    "nav.myAccount": "Akauntu Yangye",
    
    // Find Vets Page
    "findVets.title": "Shanga Abashaaho",
    "findVets.subtitle": "Kushanga abashaaho abakugu omu kitundu kyawe",
    "findVets.searchPlaceholder": "Shanga na izina, ahantu nari obumanyi...",
    "findVets.vetLocations": "Ahantu h'Abashaaho",
    "findVets.found": "Bashangiwe",
    "findVets.veterinarian": "Omushaaho",
    "findVets.veterinarians": "Abashaaho",
    "findVets.noVets": "Tihariho abashaaho bashangiwe",
    "findVets.noLocationData": "Tihariho abashaaho abaine ehantu haabo",
    "findVets.viewProfile": "Reeba Ebikumukwataho",
    "findVets.verified": "Akakasizibwe",
    "findVets.available": "Ariho",
    "findVets.online": "Ariho Hati",
    "findVets.offline": "Tari kuriho",
    "findVets.failedToLoad": "Okureeba abashaaho kuremereire",
    
    // Farmer Dashboard
    "farmerDashboard.title": "Ekibaho ky'Omuhingi",
    "farmerDashboard.subtitle": "Kurondoora ebyonyi byawe n'okubuuza",
    "farmerDashboard.requestConsultation": "Saba Okubuuza",
    "farmerDashboard.requestConsultationDesc": "Fumura obujanjabi bw'abashaaho obu ebyonyi byawe",
    "farmerDashboard.manageAnimals": "Rondoora Ebyonyi",
    "farmerDashboard.manageAnimalsDesc": "Yongyera nari hindura amakuru g'ebyonyi byawe",
    "farmerDashboard.totalAnimals": "Ebyonyi Byona",
    "farmerDashboard.pendingConsultations": "Okubuuza Okutari Kuhindurwa",
    "farmerDashboard.completedConsultations": "Okubuuza Okurangire",
    "farmerDashboard.recentConsultations": "Okubuuza Okushya",
    "farmerDashboard.recentConsultationsDesc": "Okubuuza kwawe okw'ekiseera kino",
    "farmerDashboard.noConsultations": "Tihariho okubuuza",
    "farmerDashboard.firstConsultation": "Saba Okubuuza Kwonka Okwa Mbere",
    "farmerDashboard.viewDetails": "Reeba Ebirikukwataho",
    "farmerDashboard.created": "Kyatondekwa",
    
    // Vet Dashboard
    "vetDashboard.title": "Ekibaho ky'Omushaaho",
    "vetDashboard.subtitle": "Kurondoora okubuuza n'okuyambira abahingi",
    "vetDashboard.pendingConsultations": "Okubuuza Okutari Kuhindurwa",
    "vetDashboard.inProgress": "Nikukorerwa",
    "vetDashboard.completed": "Kurangire",
    "vetDashboard.pending": "Okutari Kuhindurwa",
    "vetDashboard.myCases": "Ebintu Byangye",
    "vetDashboard.availableConsultations": "Okubuuza Okuri",
    "vetDashboard.availableConsultationsDesc": "Kwikira okubuuza kutandike okuyambira abahingi",
    "vetDashboard.noPending": "Tihariho okubuuza okutari kuhindurwa ekiseera kino",
    "vetDashboard.myConsultations": "Okubuuza Kwangye",
    "vetDashboard.myConsultationsDesc": "Okubuuza okuri kukurondoora",
    "vetDashboard.noAccepted": "Tikwetirizire okubuuza kwona",
    "vetDashboard.acceptCase": "Kwikira Kureebe Ebirikukwataho",
    "vetDashboard.manageCase": "Rondoora Ekintu",
    "vetDashboard.requested": "Kyasabwa",
    "vetDashboard.started": "Kyatandikire",
    
    // New Consultation
    "consultation.title": "Saba Okubuuza Omushaaho",
    "consultation.subtitle": "Ijuza fomu eno osabe obujanjabi bw'abashaaho",
    "consultation.selectAnimal": "Salira Ekyonyi",
    "consultation.chooseAnimal": "Salira ekyonyi",
    "consultation.noAnimals": "Tihariho ebyonyi byandikishirizibwe.",
    "consultation.addAnimalFirst": "Yongyera ekyonyi ky'okubanza",
    "consultation.subject": "Omutwe",
    "consultation.subjectPlaceholder": "Ekimanyiso ekiguhi ky'ekizibu",
    "consultation.urgencyLevel": "Omutindo gw'Obuhiise",
    "consultation.selectUrgency": "Salira obuhiise",
    "consultation.urgencyLow": "Omutindo gw'ansi - Okureeba okw'obwire",
    "consultation.urgencyMedium": "Omutindo gw'akati - Kikwetaagisa hati hati",
    "consultation.urgencyHigh": "Omutindo gw'waiguru - Obujanjabi obuhiise",
    "consultation.urgencyEmergency": "Emergenci - Embeera y'akabi",
    "consultation.symptoms": "Obumanyiso",
    "consultation.symptomsPlaceholder": "Nyomora obumanyiso obureebirwe",
    "consultation.description": "Amakuru Agamaizi",
    "consultation.descriptionPlaceholder": "Hereza amakuru agamaizi agakwata ku mbeera y'ekyonyi, enzobaano yako, n'ebindi",
    "consultation.uploadImages": "Teeka Ebifaananyi (Kwonka)",
    "consultation.clickToUpload": "Nyiga oteeke ebifaananyi (5 bya waiguru)",
    "consultation.imagesSelected": "ebifaananyi bisaliirwe",
    "consultation.cancel": "Rekaho",
    "consultation.submitRequest": "Werekeze Okusaba",
    "consultation.uploading": "Nikuteeka...",
    "consultation.submitting": "Nikuwerekeza...",
    "consultation.success": "Okusaba kwawe kwashemereziibwe bulungi",
    
    // Profile Page
    "profile.title": "Ebyensimbisa by'Ebikukwataho",
    "profile.subtitle": "Rondoora amakuru g'akauntu yawe n'ebyokwenda",
    "profile.email": "Email",
    "profile.emailCannotChange": "Email teyenda kuhindurwa",
    "profile.fullName": "Eizina Ryona",
    "profile.fullNamePlaceholder": "Andika eizina ryawe ryona",
    "profile.phoneNumber": "Esimu Namba",
    "profile.phonePlaceholder": "Andika esimu namba yawe",
    "profile.updateProfile": "Hindura Ebikukwataho",
    "profile.updating": "Nikuhindura...",
    "profile.updated": "Ebikukwataho bihindurirwe",
    "profile.updatedSuccess": "Ebikukwataho byawe bihindurirwe bulungi.",
    "profile.photoUpdated": "Ekifaananyi kihindurirwe",
    "profile.photoUpdatedSuccess": "Ekifaananyi kyawe kihindurirwe bulungi.",
    "profile.security": "Ebyensimbisa by'Obukumi",
    "profile.securityDesc": "Rondoora obukumi obu enzira ebbiri",
    "profile.googleAuth": "Google Authenticator",
    "profile.mfaEnabled": "Obukumi obu enzira ebbiri bushemererizibwe",
    "profile.mfaDisabled": "Yongyera obukumi obungi n'okwetaaga kodi okuva ku simu yawe",
    "profile.enable": "Shemerereza",
    
    // Authentication - Login
    "auth.welcomeBack": "Ogarukire",
    "auth.loginSubtitle": "Yingira okwetooke akauntu yawe eya VetConnect",
    "auth.email": "Email",
    "auth.emailPlaceholder": "email@yawe.com",
    "auth.password": "Ekigambo ky'Obukuumi",
    "auth.passwordPlaceholder": "••••••••",
    "auth.continueWithAuth": "Twesegye n'Authenticator",
    "auth.temporarilyLocked": "Kizibizibwe Okw'Ekiseera",
    "auth.verifying": "Nikukakasa...",
    "auth.noAccount": "Otaine akauntu?",
    "auth.registerHere": "Wandiishe hanu",
    "auth.authenticatorCode": "Kodi y'Authenticator",
    "auth.enterCode": "Andika kodi y'ennamba 6 okuva mu Google Authenticator",
    "auth.verificationCode": "Kodi y'Okukakasa",
    "auth.enterCodeFromApp": "Andika kodi okuva mu Google Authenticator",
    "auth.verifyAndLogin": "Kakasa Oyingire",
    "auth.back": "Garuka",
    "auth.invalidCode": "Kodi Etari Kuhurikira",
    "auth.enterSixDigits": "Andika kodi y'ennamba 6",
    "auth.validationError": "Ensobi y'Okukakasa",
    "auth.loginSuccess": "Okuyingira Kubuzire",
    "auth.mfaReminder": "Fukirira okushemerereza Google Authenticator obu obukuumi obweyongerye",
    "auth.enterAuthCode": "Andika Kodi y'Authenticator",
    "auth.openAuthApp": "Huura Google Authenticator wandike kodi y'ennamba 6",
    "auth.mfaSuccess": "Waayingire bulungi na Google Authenticator",
    "auth.timeRemaining": "Ekiseera ekisigire",
    
    // Authentication - Register
    "auth.createAccount": "Tonda Akauntu",
    "auth.registerSubtitle": "Yegatte VetConnect obone obujanjabi bw'ebyonyi",
    "auth.fullName": "Eizina Ryona",
    "auth.fullNamePlaceholder": "Abiira Kwesiga",
    "auth.confirmPassword": "Kakasa Ekigambo ky'Obukuumi",
    "auth.iAmA": "Ndi:",
    "auth.farmerPetOwner": "Omuhingi / Nyine Ebyonyi",
    "auth.farmerDesc": "Neetaaga okubuuza obu ebyonyi byangye",
    "auth.veterinarian": "Omushaaho",
    "auth.vetDesc": "Neenda okuha obujanjabi obu ebyonyi",
    "auth.creatingAccount": "Nikutonda akauntu...",
    "auth.accountCreated": "Akauntu yatondekwa bulungi!",
    "auth.hasAccount": "Oine akauntu?",
    "auth.loginHere": "Yingira hanu",
    
    // Validation messages
    "auth.invalidEmail": "Email etari kuhikira",
    "auth.passwordMinLength": "Ekigambo ky'obukuumi kikwetaagisa ennukuta 6",
    "auth.nameMinLength": "Eizina rikwetaagisa ennukuta 2",
    "auth.passwordsNoMatch": "Ebigambo by'obukuumi tibiri kukwatagana",
    
    // Animals Management
    "animals.title": "Ebyonyi Byangye",
    "animals.subtitle": "Rondoora amakuru g'ebyonyi byawe",
    "animals.addAnimal": "Yongyera Ekyonyi",
    "animals.editAnimal": "Hindura Ekyonyi",
    "animals.deleteAnimal": "Siba Ekyonyi",
    "animals.name": "Eizina",
    "animals.type": "Ekika",
    "animals.breed": "Omuzaro",
    "animals.age": "Emyaka",
    "animals.weight": "Obuzito (kg)",
    "animals.medicalHistory": "Ebyafayo by'Obujanjabi",
    "animals.noAnimals": "Tihariho ebyonyi byandikishirizibwe",
    "animals.addFirst": "Yongyera ekyonyi kyawe eky'okubanza",
    
    // Status labels
    "status.pending": "Nikwekunda",
    "status.inProgress": "Nikukorerwa",
    "status.completed": "Kurangire",
    "status.cancelled": "Kwekizibwe",
    
    // Urgency labels
    "urgency.low": "Omutindo gw'ansi",
    "urgency.medium": "Omutindo gw'akati",
    "urgency.high": "Omutindo gw'waiguru",
    "urgency.emergency": "Emergenci",
    
    // Common
    "common.loading": "Nikureeba...",
    "common.error": "Ensobi",
    "common.success": "Kibuzire",
    "common.save": "Biika",
    "common.cancel": "Rekaho",
    "common.delete": "Siba",
    "common.edit": "Hindura",
    "common.submit": "Sindika",
    "common.required": "Kikwetaagisa",
    "common.optional": "Kwonka",
    "common.unnamed": "Etaine izina",
    "common.years": "emyaka",
    "common.months": "emyezi",
    "common.you": "Iwe",
    
    // Messaging
    "messaging.title": "Obubaka",
    "messaging.subtitle": "Ebiteekateko by'okubuuza kwawe",
    "messaging.noMessages": "Tihariho Bubaka",
    "messaging.noMessagesDesc": "Tandika okubuuza otandike okutumirana n'omusawo.",
    "messaging.pendingAssignment": "Nikwetekyerezebwa",
    "messaging.consultationMessages": "Obubaka bw'Okubuuza",
    "messaging.typeMessage": "Andika obubaka bwawe...",
    "messaging.sendMessage": "Sindika obubaka",
    
    // Consultation Detail
    "consultationDetail.requestedOn": "Kyasabwa",
    "consultationDetail.assignedVet": "Omusawo Owakwatirizibwa",
    "consultationDetail.description": "Ebirikukwataho",
    "consultationDetail.symptoms": "Obumanyiso",
    "consultationDetail.images": "Ebifaananyi",
    "consultationDetail.back": "Garuka",
    "consultationDetail.failedToLoad": "Kureba okubuuza kuremere",
    "consultationDetail.diagnosis": "Okusanga Obulwaire",
    "consultationDetail.treatmentPlan": "Entekateeka y'Obujanjabi",
    "consultationDetail.followUpNotes": "Amakuru g'Okulondoora",
    
    // Theme
    "theme.light": "Ekitangaaza",
    "theme.dark": "Ekiziruguru",
    "theme.system": "System",
    
    // Language names
    "lang.en": "Engereza",
    "lang.runyankole": "Runyankole",
    "lang.rukiga": "Rukiga",
    "lang.runyoro": "Runyoro",
    "lang.rutooro": "Rutooro",
  },
  runyoro: {
    // Navigation
    "nav.findVets": "Yingura Abasawo",
    "nav.login": "Yingira",
    "nav.getStarted": "Tandika",
    "nav.dashboard": "Ekibaho",
    "nav.messages": "Obubaka",
    "nav.profile": "Ebikukukwataho",
    "nav.signOut": "Vaamu",
    "nav.myAccount": "Akauntu Yange",
    
    // Find Vets Page
    "findVets.title": "Yingura Abasawo",
    "findVets.subtitle": "Kuyingura abasawo abakugu omu kitundu kyawe",
    "findVets.searchPlaceholder": "Yingura na izina, ehantu nari obumanyi...",
    "findVets.vetLocations": "Ehantu hy'Abasawo",
    "findVets.found": "Bayinguriwe",
    "findVets.veterinarian": "Omusawo",
    "findVets.veterinarians": "Abasawo",
    "findVets.noVets": "Tihariho abasawo bayinguriwe",
    "findVets.noLocationData": "Tihariho abasawo abaine ehantu haabo",
    "findVets.viewProfile": "Reba Ebikumukwataho",
    "findVets.verified": "Akakasizibwe",
    "findVets.available": "Aliho",
    "findVets.online": "Aliho Hati",
    "findVets.offline": "Tarikuriho",
    "findVets.failedToLoad": "Okureba abasawo kuremereire",
    
    // Farmer Dashboard
    "farmerDashboard.title": "Ekibaho ky'Omuhingi",
    "farmerDashboard.subtitle": "Kurondoora ebyonyi byawe n'okubuuza",
    "farmerDashboard.requestConsultation": "Saba Okubuuza",
    "farmerDashboard.requestConsultationDesc": "Fumura obujanjabi bw'abasawo obu ebyonyi byawe",
    "farmerDashboard.manageAnimals": "Rondoora Ebyonyi",
    "farmerDashboard.manageAnimalsDesc": "Yongyera nari hindura amakuru g'ebyonyi byawe",
    "farmerDashboard.totalAnimals": "Ebyonyi Byona",
    "farmerDashboard.pendingConsultations": "Okubuuza Okutahindurwa",
    "farmerDashboard.completedConsultations": "Okubuuza Okurangire",
    "farmerDashboard.recentConsultations": "Okubuuza Okushya",
    "farmerDashboard.recentConsultationsDesc": "Okubuuza kwawe okw'ekiseera kino",
    "farmerDashboard.noConsultations": "Tihariho okubuuza",
    "farmerDashboard.firstConsultation": "Saba Okubuuza Okwa Mbere",
    "farmerDashboard.viewDetails": "Reba Ebirikukwataho",
    "farmerDashboard.created": "Kyatondekwa",
    
    // Vet Dashboard
    "vetDashboard.title": "Ekibaho ky'Omusawo",
    "vetDashboard.subtitle": "Kurondoora okubuuza n'okuyambira abahingi",
    "vetDashboard.pendingConsultations": "Okubuuza Okutahindurwa",
    "vetDashboard.inProgress": "Nikukorerwa",
    "vetDashboard.completed": "Kurangire",
    "vetDashboard.pending": "Okutahindurwa",
    "vetDashboard.myCases": "Ebintu Byange",
    "vetDashboard.availableConsultations": "Okubuuza Okuri",
    "vetDashboard.availableConsultationsDesc": "Kwikira okubuuza kutandike okuyambira abahingi",
    "vetDashboard.noPending": "Tihariho okubuuza okutahindurwa ekiseera kino",
    "vetDashboard.myConsultations": "Okubuuza Kwange",
    "vetDashboard.myConsultationsDesc": "Okubuuza okuri kukurondoora",
    "vetDashboard.noAccepted": "Tikwekiriize okubuuza kwona",
    "vetDashboard.acceptCase": "Kwikira Kurebe Ebirikukwataho",
    "vetDashboard.manageCase": "Rondoora Ekintu",
    "vetDashboard.requested": "Kyasabwa",
    "vetDashboard.started": "Kyatandikire",
    
    // New Consultation
    "consultation.title": "Saba Okubuuza Omusawo",
    "consultation.subtitle": "Ijuza fomu eno osabe obujanjabi bw'abasawo",
    "consultation.selectAnimal": "Salira Ekyonyi",
    "consultation.chooseAnimal": "Salira ekyonyi",
    "consultation.noAnimals": "Tihariho ebyonyi byandikishirizibwe.",
    "consultation.addAnimalFirst": "Yongyera ekyonyi ky'okubanza",
    "consultation.subject": "Omutwe",
    "consultation.subjectPlaceholder": "Ekimanyiso ekiguhi ky'ekizibu",
    "consultation.urgencyLevel": "Omutindo gw'Obuhiise",
    "consultation.selectUrgency": "Salira obuhiise",
    "consultation.urgencyLow": "Omutindo gw'ansi - Okureba okw'obwire",
    "consultation.urgencyMedium": "Omutindo gw'akati - Kikwetaagisa hati hati",
    "consultation.urgencyHigh": "Omutindo gw'waiguru - Obujanjabi obuhiise",
    "consultation.urgencyEmergency": "Emergenci - Embeera y'akabi",
    "consultation.symptoms": "Obumanyiso",
    "consultation.symptomsPlaceholder": "Nyomora obumanyiso oburebwe",
    "consultation.description": "Amakuru Agamaizi",
    "consultation.descriptionPlaceholder": "Hereza amakuru agamaizi agakwata ku mbeera y'ekyonyi, enzobaano yako, n'ebindi",
    "consultation.uploadImages": "Teeka Ebifaananyi (Kwonka)",
    "consultation.clickToUpload": "Nyiga oteeke ebifaananyi (5 bya waiguru)",
    "consultation.imagesSelected": "ebifaananyi bisaliirwe",
    "consultation.cancel": "Rekaho",
    "consultation.submitRequest": "Werekeze Okusaba",
    "consultation.uploading": "Nikuteeka...",
    "consultation.submitting": "Nikuwerekeza...",
    "consultation.success": "Okusaba kwawe kwashemereziibwe bulungi",
    
    // Profile Page
    "profile.title": "Ebyensimbisa by'Ebikukukwataho",
    "profile.subtitle": "Rondoora amakuru g'akauntu yawe n'ebyokwenda",
    "profile.email": "Email",
    "profile.emailCannotChange": "Email teyenda kuhindurwa",
    "profile.fullName": "Eizina Ryona",
    "profile.fullNamePlaceholder": "Andika eizina ryawe ryona",
    "profile.phoneNumber": "Esimu Namba",
    "profile.phonePlaceholder": "Andika esimu namba yawe",
    "profile.updateProfile": "Hindura Ebikukukwataho",
    "profile.updating": "Nikuhindura...",
    "profile.updated": "Ebikukukwataho bihindurirwe",
    "profile.updatedSuccess": "Ebikukukwataho byawe bihindurirwe bulungi.",
    "profile.photoUpdated": "Ekifaananyi kihindurirwe",
    "profile.photoUpdatedSuccess": "Ekifaananyi kyawe kihindurirwe bulungi.",
    "profile.security": "Ebyensimbisa by'Obukumi",
    "profile.securityDesc": "Rondoora obukumi obu enzira ebbiri",
    "profile.googleAuth": "Google Authenticator",
    "profile.mfaEnabled": "Obukumi obu enzira ebbiri bushemererizibwe",
    "profile.mfaDisabled": "Yongyera obukumi obungi n'okwetaaga kodi okuva ku simu yawe",
    "profile.enable": "Shemerereza",
    
    // Authentication - Login
    "auth.welcomeBack": "Ogarukire",
    "auth.loginSubtitle": "Yingira okwetooke akauntu yawe eya VetConnect",
    "auth.email": "Email",
    "auth.emailPlaceholder": "email@yawe.com",
    "auth.password": "Ekigambo ky'Obukuumi",
    "auth.passwordPlaceholder": "••••••••",
    "auth.continueWithAuth": "Twesegye n'Authenticator",
    "auth.temporarilyLocked": "Kizibizibwe Okw'Ekiseera",
    "auth.verifying": "Nikukakasa...",
    "auth.noAccount": "Otaine akauntu?",
    "auth.registerHere": "Wandiishe hanu",
    "auth.authenticatorCode": "Kodi y'Authenticator",
    "auth.enterCode": "Andika kodi y'ennamba 6 okuva mu Google Authenticator",
    "auth.verificationCode": "Kodi y'Okukakasa",
    "auth.enterCodeFromApp": "Andika kodi okuva mu Google Authenticator",
    "auth.verifyAndLogin": "Kakasa Oyingire",
    "auth.back": "Garuka",
    "auth.invalidCode": "Kodi Etari Kuhurikira",
    "auth.enterSixDigits": "Andika kodi y'ennamba 6",
    "auth.validationError": "Ensobi y'Okukakasa",
    "auth.loginSuccess": "Okuyingira Kubuzire",
    "auth.mfaReminder": "Fukirira okushemerereza Google Authenticator obu obukuumi obweyongerye",
    "auth.enterAuthCode": "Andika Kodi y'Authenticator",
    "auth.openAuthApp": "Huura Google Authenticator wandike kodi y'ennamba 6",
    "auth.mfaSuccess": "Waayingire bulungi na Google Authenticator",
    "auth.timeRemaining": "Ekiseera ekisigire",
    
    // Authentication - Register
    "auth.createAccount": "Tonda Akauntu",
    "auth.registerSubtitle": "Yegatte VetConnect obone obujanjabi bw'ebyonyi",
    "auth.fullName": "Eizina Ryona",
    "auth.fullNamePlaceholder": "Abiira Kwesiga",
    "auth.confirmPassword": "Kakasa Ekigambo ky'Obukuumi",
    "auth.iAmA": "Ndi:",
    "auth.farmerPetOwner": "Omuhingi / Nyine Ebyonyi",
    "auth.farmerDesc": "Neetaaga okubuuza obu ebyonyi byange",
    "auth.veterinarian": "Omusawo",
    "auth.vetDesc": "Neenda okuha obujanjabi obu ebyonyi",
    "auth.creatingAccount": "Nikutonda akauntu...",
    "auth.accountCreated": "Akauntu yatondekwa bulungi!",
    "auth.hasAccount": "Oine akauntu?",
    "auth.loginHere": "Yingira hanu",
    
    // Validation messages
    "auth.invalidEmail": "Email etari kuhikira",
    "auth.passwordMinLength": "Ekigambo ky'obukuumi kikwetaagisa ennukuta 6",
    "auth.nameMinLength": "Eizina rikwetaagisa ennukuta 2",
    "auth.passwordsNoMatch": "Ebigambo by'obukuumi tibiri kukwatagana",
    
    // Animals Management
    "animals.title": "Ebyonyi Byange",
    "animals.subtitle": "Rondoora amakuru g'ebyonyi byawe",
    "animals.addAnimal": "Yongyera Ekyonyi",
    "animals.editAnimal": "Hindura Ekyonyi",
    "animals.deleteAnimal": "Siba Ekyonyi",
    "animals.name": "Eizina",
    "animals.type": "Ekika",
    "animals.breed": "Omuzaro",
    "animals.age": "Emyaka",
    "animals.weight": "Obuzito (kg)",
    "animals.medicalHistory": "Ebyafayo by'Obujanjabi",
    "animals.noAnimals": "Tihariho ebyonyi byandikishirizibwe",
    "animals.addFirst": "Yongyera ekyonyi kyawe eky'okubanza",
    
    // Status labels
    "status.pending": "Nikwekunda",
    "status.inProgress": "Nikukorerwa",
    "status.completed": "Kurangire",
    "status.cancelled": "Kwekizibwe",
    
    // Urgency labels
    "urgency.low": "Omutindo gw'ansi",
    "urgency.medium": "Omutindo gw'akati",
    "urgency.high": "Omutindo gw'waiguru",
    "urgency.emergency": "Emergenci",
    
    // Common
    "common.loading": "Nikuleba...",
    "common.error": "Ensobi",
    "common.success": "Kibuzire",
    "common.save": "Biika",
    "common.cancel": "Rekaho",
    "common.delete": "Siba",
    "common.edit": "Hindura",
    "common.submit": "Sindika",
    "common.required": "Kikwetaagisa",
    "common.optional": "Kwonka",
    "common.unnamed": "Etaine izina",
    "common.years": "emyaka",
    "common.months": "emyezi",
    "common.you": "Iwe",
    
    // Messaging
    "messaging.title": "Obubaka",
    "messaging.subtitle": "Ebiteekateko by'okubuuza kwawe",
    "messaging.noMessages": "Tihariho Bubaka",
    "messaging.noMessagesDesc": "Tandika okubuuza otandike okutumirana n'omusawo.",
    "messaging.pendingAssignment": "Nikwetekyerezebwa",
    "messaging.consultationMessages": "Obubaka bw'Okubuuza",
    "messaging.typeMessage": "Andika obubaka bwawe...",
    "messaging.sendMessage": "Sindika obubaka",
    
    // Consultation Detail
    "consultationDetail.requestedOn": "Kyasabwa",
    "consultationDetail.assignedVet": "Omusawo Owakwatirizibwa",
    "consultationDetail.description": "Ebirikukwataho",
    "consultationDetail.symptoms": "Obumanyiso",
    "consultationDetail.images": "Ebifaananyi",
    "consultationDetail.back": "Garuka",
    "consultationDetail.failedToLoad": "Kureba okubuuza kuremere",
    "consultationDetail.diagnosis": "Okusanga Obulwaire",
    "consultationDetail.treatmentPlan": "Entekateeka y'Obujanjabi",
    "consultationDetail.followUpNotes": "Amakuru g'Okulondoora",
    
    // Theme
    "theme.light": "Ekitangaala",
    "theme.dark": "Ekiziruguru",
    "theme.system": "System",
    
    // Language names
    "lang.en": "Engereza",
    "lang.runyankole": "Runyankole",
    "lang.rukiga": "Rukiga",
    "lang.runyoro": "Runyoro",
    "lang.rutooro": "Rutooro",
  },
  rutooro: {
    // Navigation
    "nav.findVets": "Bwera Abasawo",
    "nav.login": "Yingira",
    "nav.getStarted": "Tandika",
    "nav.dashboard": "Ekibaho",
    "nav.messages": "Obubaka",
    "nav.profile": "Ebikukukwataho",
    "nav.signOut": "Vaamu",
    "nav.myAccount": "Akauntu Yange",
    
    // Find Vets Page
    "findVets.title": "Bwera Abasawo",
    "findVets.subtitle": "Kubwera abasawo abakugu omu kitundu kyawe",
    "findVets.searchPlaceholder": "Bwera na izina, ehantu nari obumanyi...",
    "findVets.vetLocations": "Ahantu h'Abasawo",
    "findVets.found": "Babwerirwe",
    "findVets.veterinarian": "Omusawo",
    "findVets.veterinarians": "Abasawo",
    "findVets.noVets": "Tihariho abasawo babwerirwe",
    "findVets.noLocationData": "Tihariho abasawo abaine ehantu haabo",
    "findVets.viewProfile": "Reba Ebikumukwataho",
    "findVets.verified": "Akakasizibwe",
    "findVets.available": "Aliho",
    "findVets.online": "Aliho Hati",
    "findVets.offline": "Tarikuriho",
    "findVets.failedToLoad": "Okureba abasawo kuremereire",
    
    // Farmer Dashboard
    "farmerDashboard.title": "Ekibaho ky'Omuhingi",
    "farmerDashboard.subtitle": "Kurondoora ebyonyi byawe n'okubuuza",
    "farmerDashboard.requestConsultation": "Saba Okubuuza",
    "farmerDashboard.requestConsultationDesc": "Fumura obujanjabi bw'abasawo obu ebyonyi byawe",
    "farmerDashboard.manageAnimals": "Rondoora Ebyonyi",
    "farmerDashboard.manageAnimalsDesc": "Yongyera nari hindura amakuru g'ebyonyi byawe",
    "farmerDashboard.totalAnimals": "Ebyonyi Byona",
    "farmerDashboard.pendingConsultations": "Okubuuza Okutahindurwa",
    "farmerDashboard.completedConsultations": "Okubuuza Okurangire",
    "farmerDashboard.recentConsultations": "Okubuuza Okushya",
    "farmerDashboard.recentConsultationsDesc": "Okubuuza kwawe okw'ekiseera kino",
    "farmerDashboard.noConsultations": "Tihariho okubuuza",
    "farmerDashboard.firstConsultation": "Saba Okubuuza Okwa Mbere",
    "farmerDashboard.viewDetails": "Reba Ebirikukwataho",
    "farmerDashboard.created": "Kyatondekwa",
    
    // Vet Dashboard
    "vetDashboard.title": "Ekibaho ky'Omusawo",
    "vetDashboard.subtitle": "Kurondoora okubuuza n'okuyambira abahingi",
    "vetDashboard.pendingConsultations": "Okubuuza Okutahindurwa",
    "vetDashboard.inProgress": "Nikukorerwa",
    "vetDashboard.completed": "Kurangire",
    "vetDashboard.pending": "Okutahindurwa",
    "vetDashboard.myCases": "Ebintu Byange",
    "vetDashboard.availableConsultations": "Okubuuza Okuri",
    "vetDashboard.availableConsultationsDesc": "Kwikira okubuuza kutandike okuyambira abahingi",
    "vetDashboard.noPending": "Tihariho okubuuza okutahindurwa ekiseera kino",
    "vetDashboard.myConsultations": "Okubuuza Kwange",
    "vetDashboard.myConsultationsDesc": "Okubuuza okuri kukurondoora",
    "vetDashboard.noAccepted": "Tikwekiriize okubuuza kwona",
    "vetDashboard.acceptCase": "Kwikira Kurebe Ebirikukwataho",
    "vetDashboard.manageCase": "Rondoora Ekintu",
    "vetDashboard.requested": "Kyasabwa",
    "vetDashboard.started": "Kyatandikire",
    
    // New Consultation
    "consultation.title": "Saba Okubuuza Omusawo",
    "consultation.subtitle": "Ijuza fomu eno osabe obujanjabi bw'abasawo",
    "consultation.selectAnimal": "Salira Ekyonyi",
    "consultation.chooseAnimal": "Salira ekyonyi",
    "consultation.noAnimals": "Tihariho ebyonyi byandikishirizibwe.",
    "consultation.addAnimalFirst": "Yongyera ekyonyi ky'okubanza",
    "consultation.subject": "Omutwe",
    "consultation.subjectPlaceholder": "Ekimanyiso ekiguhi ky'ekizibu",
    "consultation.urgencyLevel": "Omutindo gw'Obuhiise",
    "consultation.selectUrgency": "Salira obuhiise",
    "consultation.urgencyLow": "Omutindo gw'ansi - Okureba okw'obwire",
    "consultation.urgencyMedium": "Omutindo gw'akati - Kikwetaagisa hati hati",
    "consultation.urgencyHigh": "Omutindo gw'waiguru - Obujanjabi obuhiise",
    "consultation.urgencyEmergency": "Emergenci - Embeera y'akabi",
    "consultation.symptoms": "Obumanyiso",
    "consultation.symptomsPlaceholder": "Nyomora obumanyiso oburebwe",
    "consultation.description": "Amakuru Agamaizi",
    "consultation.descriptionPlaceholder": "Hereza amakuru agamaizi agakwata ku mbeera y'ekyonyi, enzobaano yako, n'ebindi",
    "consultation.uploadImages": "Teeka Ebifaananyi (Kwonka)",
    "consultation.clickToUpload": "Nyiga oteeke ebifaananyi (5 bya waiguru)",
    "consultation.imagesSelected": "ebifaananyi bisaliirwe",
    "consultation.cancel": "Rekaho",
    "consultation.submitRequest": "Werekeze Okusaba",
    "consultation.uploading": "Nikuteeka...",
    "consultation.submitting": "Nikuwerekeza...",
    "consultation.success": "Okusaba kwawe kwashemereziibwe bulungi",
    
    // Profile Page
    "profile.title": "Ebyensimbisa by'Ebikukukwataho",
    "profile.subtitle": "Rondoora amakuru g'akauntu yawe n'ebyokwenda",
    "profile.email": "Email",
    "profile.emailCannotChange": "Email teyenda kuhindurwa",
    "profile.fullName": "Eizina Ryona",
    "profile.fullNamePlaceholder": "Andika eizina ryawe ryona",
    "profile.phoneNumber": "Esimu Namba",
    "profile.phonePlaceholder": "Andika esimu namba yawe",
    "profile.updateProfile": "Hindura Ebikukukwataho",
    "profile.updating": "Nikuhindura...",
    "profile.updated": "Ebikukukwataho bihindurirwe",
    "profile.updatedSuccess": "Ebikukukwataho byawe bihindurirwe bulungi.",
    "profile.photoUpdated": "Ekifaananyi kihindurirwe",
    "profile.photoUpdatedSuccess": "Ekifaananyi kyawe kihindurirwe bulungi.",
    "profile.security": "Ebyensimbisa by'Obukumi",
    "profile.securityDesc": "Rondoora obukumi obu enzira ebbiri",
    "profile.googleAuth": "Google Authenticator",
    "profile.mfaEnabled": "Obukumi obu enzira ebbiri bushemererizibwe",
    "profile.mfaDisabled": "Yongyera obukumi obungi n'okwetaaga kodi okuva ku simu yawe",
    "profile.enable": "Shemerereza",
    
    // Authentication - Login
    "auth.welcomeBack": "Ogarukire",
    "auth.loginSubtitle": "Yingira okwetooke akauntu yawe eya VetConnect",
    "auth.email": "Email",
    "auth.emailPlaceholder": "email@yawe.com",
    "auth.password": "Ekigambo ky'Obukuumi",
    "auth.passwordPlaceholder": "••••••••",
    "auth.continueWithAuth": "Twesegye n'Authenticator",
    "auth.temporarilyLocked": "Kizibizibwe Okw'Ekiseera",
    "auth.verifying": "Nikukakasa...",
    "auth.noAccount": "Otaine akauntu?",
    "auth.registerHere": "Wandiishe hanu",
    "auth.authenticatorCode": "Kodi y'Authenticator",
    "auth.enterCode": "Andika kodi y'ennamba 6 okuva mu Google Authenticator",
    "auth.verificationCode": "Kodi y'Okukakasa",
    "auth.enterCodeFromApp": "Andika kodi okuva mu Google Authenticator",
    "auth.verifyAndLogin": "Kakasa Oyingire",
    "auth.back": "Garuka",
    "auth.invalidCode": "Kodi Etari Kuhurikira",
    "auth.enterSixDigits": "Andika kodi y'ennamba 6",
    "auth.validationError": "Ensobi y'Okukakasa",
    "auth.loginSuccess": "Okuyingira Kubuzire",
    "auth.mfaReminder": "Fukirira okushemerereza Google Authenticator obu obukuumi obweyongerye",
    "auth.enterAuthCode": "Andika Kodi y'Authenticator",
    "auth.openAuthApp": "Huura Google Authenticator wandike kodi y'ennamba 6",
    "auth.mfaSuccess": "Waayingire bulungi na Google Authenticator",
    "auth.timeRemaining": "Ekiseera ekisigire",
    
    // Authentication - Register
    "auth.createAccount": "Tonda Akauntu",
    "auth.registerSubtitle": "Yegatte VetConnect obone obujanjabi bw'ebyonyi",
    "auth.fullName": "Eizina Ryona",
    "auth.fullNamePlaceholder": "Abiira Kwesiga",
    "auth.confirmPassword": "Kakasa Ekigambo ky'Obukuumi",
    "auth.iAmA": "Ndi:",
    "auth.farmerPetOwner": "Omuhingi / Nyine Ebyonyi",
    "auth.farmerDesc": "Neetaaga okubuuza obu ebyonyi byange",
    "auth.veterinarian": "Omusawo",
    "auth.vetDesc": "Neenda okuha obujanjabi obu ebyonyi",
    "auth.creatingAccount": "Nikutonda akauntu...",
    "auth.accountCreated": "Akauntu yatondekwa bulungi!",
    "auth.hasAccount": "Oine akauntu?",
    "auth.loginHere": "Yingira hanu",
    
    // Validation messages
    "auth.invalidEmail": "Email etari kuhikira",
    "auth.passwordMinLength": "Ekigambo ky'obukuumi kikwetaagisa ennukuta 6",
    "auth.nameMinLength": "Eizina rikwetaagisa ennukuta 2",
    "auth.passwordsNoMatch": "Ebigambo by'obukuumi tibiri kukwatagana",
    
    // Animals Management
    "animals.title": "Ebyonyi Byange",
    "animals.subtitle": "Rondoora amakuru g'ebyonyi byawe",
    "animals.addAnimal": "Yongyera Ekyonyi",
    "animals.editAnimal": "Hindura Ekyonyi",
    "animals.deleteAnimal": "Siba Ekyonyi",
    "animals.name": "Eizina",
    "animals.type": "Ekika",
    "animals.breed": "Omuzaro",
    "animals.age": "Emyaka",
    "animals.weight": "Obuzito (kg)",
    "animals.medicalHistory": "Ebyafayo by'Obujanjabi",
    "animals.noAnimals": "Tihariho ebyonyi byandikishirizibwe",
    "animals.addFirst": "Yongyera ekyonyi kyawe eky'okubanza",
    
    // Status labels
    "status.pending": "Nikwekunda",
    "status.inProgress": "Nikukorerwa",
    "status.completed": "Kurangire",
    "status.cancelled": "Kwekizibwe",
    
    // Urgency labels
    "urgency.low": "Omutindo gw'ansi",
    "urgency.medium": "Omutindo gw'akati",
    "urgency.high": "Omutindo gw'waiguru",
    "urgency.emergency": "Emergenci",
    
    // Common
    "common.loading": "Nikuleba...",
    "common.error": "Ensobi",
    "common.success": "Kibuzire",
    "common.save": "Biika",
    "common.cancel": "Rekaho",
    "common.delete": "Siba",
    "common.edit": "Hindura",
    "common.submit": "Sindika",
    "common.required": "Kikwetaagisa",
    "common.optional": "Kwonka",
    "common.unnamed": "Etaine izina",
    "common.years": "emyaka",
    "common.months": "emyezi",
    "common.you": "Iwe",
    
    // Messaging
    "messaging.title": "Obubaka",
    "messaging.subtitle": "Ebiteekateko by'okubuuza kwawe",
    "messaging.noMessages": "Tihariho Bubaka",
    "messaging.noMessagesDesc": "Tandika okubuuza otandike okutumirana n'omusawo.",
    "messaging.pendingAssignment": "Nikwetekyerezebwa",
    "messaging.consultationMessages": "Obubaka bw'Okubuuza",
    "messaging.typeMessage": "Andika obubaka bwawe...",
    "messaging.sendMessage": "Sindika obubaka",
    
    // Consultation Detail
    "consultationDetail.requestedOn": "Kyasabwa",
    "consultationDetail.assignedVet": "Omusawo Owakwatirizibwa",
    "consultationDetail.description": "Ebirikukwataho",
    "consultationDetail.symptoms": "Obumanyiso",
    "consultationDetail.images": "Ebifaananyi",
    "consultationDetail.back": "Garuka",
    "consultationDetail.failedToLoad": "Kureba okubuuza kuremere",
    "consultationDetail.diagnosis": "Okusanga Obulwaire",
    "consultationDetail.treatmentPlan": "Entekateeka y'Obujanjabi",
    "consultationDetail.followUpNotes": "Amakuru g'Okulondoora",
    
    // Theme
    "theme.light": "Ekitangaala",
    "theme.dark": "Ekiziruguru",
    "theme.system": "System",
    
    // Language names
    "lang.en": "Engereza",
    "lang.runyankole": "Runyankole",
    "lang.rukiga": "Rukiga",
    "lang.runyoro": "Runyoro",
    "lang.rutooro": "Rutooro",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
